import AnimatedNumber from "./animatedNumber";

export default function Stats() {
  const content = {
    title: "Empowering Innovation Through Digital Solutions",
    titleClass: "text-4xl font-bold text-white text-center mb-4",
    description:
      "At ITIDCS, we're driving the future with scalable tech, impactful training, and trusted services. Here's a quick look at our progress and impact.",
    descriptionClass: "text-lg text-gray-300 text-center mb-12",
    containerClass: "bg-[#0f172a] py-20 px-6",
    wrapperClass: "max-w-7xl mx-auto",
    headerClass: "mb-12",
    statsContainerClass: "grid grid-cols-1 md:grid-cols-3 gap-12",
  };

  const stats = [
    {
      id: 1,
      name: "Active Learners Enrolled",
      nameClass: "text-xl font-semibold text-white mb-2",
      value: 5000,
      valueClass: "text-4xl font-extrabold text-blue-400",
      description: "Thousands of students enrolled in career-focused courses.",
      descriptionClass: "text-gray-400",
      className: "bg-[#1e293b] p-6 rounded-xl shadow-md hover:shadow-blue-500/30 transition duration-300",
    },
    {
      id: 2,
      name: "Revenue Generated by Clients",
      nameClass: "text-xl font-semibold text-white mb-2",
      value: 1200000,
      valueClass: "text-4xl font-extrabold text-green-400",
      description: "Clients using ITIDCS-developed apps and platforms worldwide.",
      descriptionClass: "text-gray-400",
      className: "bg-[#1e293b] p-6 rounded-xl shadow-md hover:shadow-green-500/30 transition duration-300",
    },
    {
      id: 3,
      name: "Successful Projects Delivered",
      nameClass: "text-xl font-semibold text-white mb-2",
      value: 150,
      valueClass: "text-4xl font-extrabold text-yellow-400",
      description: "Custom software, mobile apps, and cloud solutions deployed.",
      descriptionClass: "text-gray-400",
      className: "bg-[#1e293b] p-6 rounded-xl shadow-md hover:shadow-yellow-500/30 transition duration-300",
    },
  ];

  return (
    <div className={content.containerClass}>
      <div className={content.wrapperClass}>
        {/* Header */}
        <div className={content.headerClass}>
          <h2 className={content.titleClass}>{content.title}</h2>
          <p className={content.descriptionClass}>{content.description}</p>
        </div>

        {/* Stats Section */}
        <div className={content.statsContainerClass}>
          {stats.map((stat) => (
            <div key={stat.id} className={stat.className}>
              <p className={stat.valueClass}>
                <AnimatedNumber target={stat.value} />
              </p>
              <div>
                <p className={stat.nameClass}>{stat.name}</p>
                <p className={stat.descriptionClass}>{stat.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}